.PHONY: clean All

All:
	@echo "----------Building project:[ sectionChallenge - Debug ]----------"
	@cd "project1" && "$(MAKE)" -f  "sectionChallenge.mk"
clean:
	@echo "----------Cleaning project:[ sectionChallenge - Debug ]----------"
	@cd "project1" && "$(MAKE)" -f  "sectionChallenge.mk" clean
