.PHONY: clean All

All:
	@echo "----------Building project:[ section8SectionChallenge - Debug ]----------"
	@cd "section8SectionChallenge" && "$(MAKE)" -f  "section8SectionChallenge.mk"
clean:
	@echo "----------Cleaning project:[ section8SectionChallenge - Debug ]----------"
	@cd "section8SectionChallenge" && "$(MAKE)" -f  "section8SectionChallenge.mk" clean
